### ISSUE TITLE
[CI][macOS] platform build fails on core_graphics symbols

### ISSUE THREAD

**Issue by kura120** [ontic-ai/sena#82]
## Summary

macOS CI is failing to build the `platform` crate in PR #80 because several `core_graphics::sys::*` symbols used in the macOS backend cannot be resolved.

## Observed Failure

- Workflow: PR #80 CI (`macos-latest`)
- Stage: `Build`
- Failure excerpt:

```text
error[E0425]: cannot find function, tuple struct or tuple variant `CGImageGetWidth` in module `core_graphics::sys`
error[E0425]: cannot find function, tuple struct or tuple variant `CGImageGetHeight` in module `core_graphics::sys`
error[E0425]: cannot find function, tuple struct or tuple variant `CGImageGetBytesPerRow` in module `core_graphics::sys`
error[E0425]: cannot find function, tuple struct or tuple variant `CGImageGetDataProvider` in module `core_graphics::sys`
error[E0425]: cannot find function, tuple struct or tuple variant `CGImageRelease` in module `core_graphics::sys`
error[E0425]: cannot find function, tuple struct or tuple variant `CGDataProviderCopyData` in module `core_graphics::sys`
error[E0425]: cannot find function, tuple struct or tuple variant `CFDataGetLength` in module `core_graphics::sys`
error[E0425]: cannot find function, tuple struct or tuple variant `CFDataGetBytePtr` in module `core_graphics::sys`
error[E0425]: cannot find function, tuple struct or tuple variant `CFRelease` in module `core_graphics::sys`
```

## Notes

- The failing source is the macOS platform backend around `crates/platform/src/macos.rs`.
- This issue is being filed so PR #80 can be merged under the temporary CI waiver tracked in `sena/docs/_scratch/daemon-cli-split.md`.

## Scope To Investigate

- Verify the correct API surface for the `core-graphics` crate version in use
- Replace invalid `core_graphics::sys::*` calls with supported bindings or the correct FFI path
- Confirm the macOS backend still meets the intended screen-capture behavior after the fix

## Expected Outcome

- `platform` builds cleanly on macOS CI
- The CI waiver can be removed once this and the other CI follow-up issues are resolved

**Comment by kura120** [comment]
Tracked under the temporary CI-waiver policy recorded in sena/docs/_scratch/daemon-cli-split.md on dev. PR #80 was merged under that temporary waiver after issues #81, #82, and #83 were filed. This issue is the dedicated follow-up for the macOS core_graphics build failures.
